Repository exercism/haxe, pull requests merged in 2023-10, with the labels that each got.

#268 Remove stray files
  exercises/robot-simulator/.meta/tests.toml
  exercises/robot-simulator/README.md
Labels: x:rep/tiny

#272 Add pending test info
  docs/TESTS.md
Labels: x:rep/tiny

#277 Format track config
  config.json
Labels: x:rep/tiny

#275 First pass at exercise difficulty levels
  config.json
Labels: x:type/content, x:rep/small

#60 Add allergies exercise
  config.json
  exercises/practice/allergies/.docs/instructions.md
  exercises/practice/allergies/.meta/Example.hx
  exercises/practice/allergies/.meta/config.json
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/src/Allergies.hx
  exercises/practice/allergies/test.hxml
  exercises/practice/allergies/test/Test.hx
Labels: x:module/practice-exercise, x:rep/medium
